- Contracts
    - artifacts
    - interfaces
        - pool
            - artifacts
            - IUniswapV3PoolActions.sol
            - IUniswapV3PoolDerivedState.sol
            - IUniswapV3PoolEvents.sol
            - IUniswapV3PoolImmutables.sol
            - IUniswapV3PoolOwnerActions.sol
            - IUniswapV3PoolState.sol
        - callback 
            - IUniswapV3FlashCallback.sol
            - IUniswapV3MintCallback.sol
            - IUniswapV3SwapCallback.sol
        - artifacts
        - IUniswapV3PoolDeployer.sol
        - IUniswapV3Pool.sol
        - IUniswapV3Factory.sol
        - IERC20Minimal.sol
        - ISwapRouter.sol
        - IWETH9.sol 
    - libraries
        - artifacts
        - BitMath.sol
        - FixedPoint128.sol
        - FixedPoint96.sol
        - FullMath.sol
        - LiquidityMath.sol
        - LowGasSafeMath.sol
        - Oracle.sol
        - Position.sol
        - SafeCast.sol
        - SqrtPriceMath.sol
        - SwapMath.sol
        - Tick.sol
        - TickBitmap.sol
        - TickMath.sol
        - TransferHelper.sol
        - UnsafeMath.sol
    - UniswapV3Pool.sol
    - UniswapV3Factory.sol
    - token.sol
    - snipe.sol
    -UniswapV3PoolDeployer
    -WETH9.sol
    -NoDelegateCall.sol
    - (other files)
